name: Release Packages

on:
  push:
    branches: [master]

jobs:
  release:
    name: Release Packages
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'Publish')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-node-14-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn bootstrap
      - run: yarn constraints
      - run: yarn typecheck:all
      - run: yarn workspaces foreach -Apv run build
      - uses: actions/upload-artifact@v2
        with:
          name: bundles
          path: packages/*/bundles/**/*.js
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
